"""Per-parcel economics for nature-based interventions.

Every number a parcel contributes to the plan — cost, avoided expected loss,
sequestered carbon, and household income — flows from the single ``FACTORS``
table below.  That table is the project's honesty backbone: each entry carries a
``source`` string and every figure is screening-grade, not a site engineering
estimate.  The optimizer never invents a coefficient; it only combines these.
"""
from __future__ import annotations

from typing import Iterable

# Screening-grade unit economics per intervention type.  These are deliberately
# conservative, citable ranges, not site-specific designs.  ``eal_reduction_frac``
# is the fraction of the *covered cells'* expected annual loss that a mature
# stand of this type can avoid, bundling both its physical efficacy and the share
# of local hazard it actually targets (slope stabilisation vs. flood attenuation).
FACTORS: dict[str, dict[str, object]] = {
    "vetiver_slope": {
        "cost_per_ha": 5000.0,
        "eal_reduction_frac": 0.35,
        "primary_hazard": "landslide",
        "co2_t_per_ha_10yr": 12.0,
        "income_usd_per_ha_yr": 600.0,
        "source": "Vetiver hedgerows cut slope erosion >90% (Truong et al.); cost/income from ICIMOD bioengineering field costings.",
    },
    "bamboo_slope": {
        "cost_per_ha": 4000.0,
        "eal_reduction_frac": 0.30,
        "primary_hazard": "landslide",
        "co2_t_per_ha_10yr": 45.0,
        "income_usd_per_ha_yr": 850.0,
        "source": "Bamboo root reinforcement for shallow landslides; bamboo is an established Nepali rural cash crop (INBAR).",
    },
    "floodplain_restore": {
        "cost_per_ha": 8000.0,
        "eal_reduction_frac": 0.30,
        "primary_hazard": "flood",
        "co2_t_per_ha_10yr": 35.0,
        "income_usd_per_ha_yr": 300.0,
        "source": "NbS flood-depth reduction ~15-40% (UNEP); floodplain reconnection costs from World Bank NbS catalogue.",
    },
    "wetland_restore": {
        "cost_per_ha": 12000.0,
        "eal_reduction_frac": 0.35,
        "primary_hazard": "flood",
        "co2_t_per_ha_10yr": 60.0,
        "income_usd_per_ha_yr": 400.0,
        "source": "Wetland attenuation of peak flows; high soil-carbon uptake (Ramsar / IPCC wetlands supplement).",
    },
    "afforestation": {
        "cost_per_ha": 3000.0,
        "eal_reduction_frac": 0.20,
        "primary_hazard": "landslide",
        "co2_t_per_ha_10yr": 80.0,
        "income_usd_per_ha_yr": 250.0,
        "source": "Catchment afforestation for slope stability and infiltration; sequestration from IPCC AFOLU defaults.",
    },
    "riverbank_bio": {
        "cost_per_ha": 6000.0,
        "eal_reduction_frac": 0.25,
        "primary_hazard": "flood",
        "co2_t_per_ha_10yr": 20.0,
        "income_usd_per_ha_yr": 500.0,
        "source": "Bioengineered riverbank protection (live crib walls, brush layering) per ICIMOD/DSCWM manuals.",
    },
}

# Fraction of a household's expected people-risk avoided that maps to one
# benefiting household — used only to report a headline household count.
PEOPLE_PER_HOUSEHOLD = 4.5


def factor(parcel_type: str) -> dict[str, object]:
    """Return the economics factor row for ``parcel_type`` or raise for an unknown type."""
    try:
        return FACTORS[parcel_type]
    except KeyError as exc:
        raise ValueError(f"Unknown intervention type {parcel_type!r}; not in FACTORS table.") from exc


def parcel_cost(parcel: dict[str, object]) -> float:
    """Capital cost of implementing a parcel, in USD."""
    row = factor(str(parcel["type"]))
    return float(row["cost_per_ha"]) * float(parcel["area_ha"])


def parcel_co2_10yr(parcel: dict[str, object]) -> float:
    """Ten-year CO2 sequestration for a parcel, in tonnes."""
    row = factor(str(parcel["type"]))
    return float(row["co2_t_per_ha_10yr"]) * float(parcel["area_ha"])


def parcel_income_yr(parcel: dict[str, object]) -> float:
    """Annual household income generated by a parcel, in USD/year."""
    row = factor(str(parcel["type"]))
    return float(row["income_usd_per_ha_yr"]) * float(parcel["area_ha"])


def eal_reduction_frac(parcel: dict[str, object]) -> float:
    """Fraction of covered-cell expected annual loss this parcel can avoid."""
    return float(factor(str(parcel["type"]))["eal_reduction_frac"])


def factor_table() -> list[dict[str, object]]:
    """Return the factor table as a flat, display-ready list of rows."""
    return [{"type": name, **row} for name, row in FACTORS.items()]


def validate_candidates(candidates: Iterable[dict[str, object]]) -> None:
    """Fail fast if any candidate references an unpriced intervention type."""
    for parcel in candidates:
        factor(str(parcel["type"]))
